name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: s1-deployment
    env: 
      BUILD_DIR: build/
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true
      - name: Build
        run: hugo --minify
        
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SOURCE: ${{ env.BUILD_DIR }}
          TARGET: ${{ vars.DEPLOY_DIR }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SCRIPT_AFTER: echo $RSYNC_STDOUT
